### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by smjure** [TechLearnersInc/cythonizer#2]
Thank you for the module. I made simple test file cython_study.pyx:
```
cpdef int test(int x):
    cdef int y = 0
    cdef int i
    for i in range(x):
        y += i
    return y
```
command `cythonizer cython_study.pyx` compiles the file successfully, but when I run `import cython_study` there's 'ModuleNotFoundError'. On the other hand, if I use conventional `setup.py` & `python setup.py build_ext --inplace`:
```
from distutils.core import setup
from Cython.Build import cythonize

setup(ext_modules = cythonize('cython_study.pyx'))
```
the import cython_study runs without errors. The observed difference is in output files at compilation. In cythonizer case output was: `cython_study.pypy36-pp73-x86_64-linux-gnu.so` and in conventional was: `cython_study.cpython-36m-x86_64-linux-gnu.so`.

I'm still at learning stage, so any idea how to solve import the `cython_study.pypy36-pp73-x86_64-linux-gnu.so` or solve the problem? Thank you.

**Comment by Rizwan-Hasan** [comment]
Have you used pypy? 

If the answer is yes then in which case you have used pypy? With cythonizer or conventional method?

**Comment by Rizwan-Hasan** [comment]
I've already tested it with pypy and python. 
If you use pypy then no matter what you use, conventional way or cythonizer, it will give you file "*.cpython-36m-x86_64-linux-gnu.so".

On the other hand, if you use python and the same will happen for both case and give you file "*.cpython-36m-x86_64-linux-gnu.so"

**Comment by Rizwan-Hasan** [comment]
**Things I've found on my test.**

> * **You can't import files cythonized with pypy into python,**
> * **And also you can't import files cythonized with python into pypy.**

**Comment by smjure** [comment]
Thanks for the answer. I have not explicitly used pypy, have just executed the code and lines exactly as stated in original post, that's it. However, I do have installed pypy on comp, but it's confusing for me too how pypy or its extension came into action. Perhaps comparing/debugging workflows of `python setup.py build_ext --inplace` and `cythonizer cython_study.pyx` would give some answers.

**Comment by Rizwan-Hasan** [comment]
Do you have any more questions or issues?

**Comment by smjure** [comment]
hope you find the reason and upgrade the module. Otherwise no Qs anymore, thanks for sharing the module.

**Comment by Rizwan-Hasan** [comment]
Okay, Thanks.
