### ISSUE TITLE
Duty of notification of license for *.pyd by cythonizer?

### ISSUE THREAD

**Issue by MKdays** [TechLearnersInc/cythonizer#3]
Thank you for making it easy to use Cython.

by the way,

Is there an obligation to notify MIT license for the result of converting my Python project to pyd through cythonizer?

I want you to clearly. Thank you.

**Comment by Rizwan-Hasan** [comment]
There is no need to notify. Thanks.

**Comment by Rizwan-Hasan** [comment]
**I'm closing this issue. If you've any more confusion, you're always welcome to create a new one.**
